// Placeholder: auto-generated by `npm run db:types` after running migrations.
// Run `npm run db:migration:up` to populate this file with the full types.
export type Database = Record<string, never>;
