-- ═══════════════════════════════════════════════════════════════════
-- Kontext Migration: Activity Events + User Preferences
-- ═══════════════════════════════════════════════════════════════════

-- ────────────────────────────────────────────
-- 1. Activity Events table
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.activity_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  repo_full_name text,
  source text NOT NULL DEFAULT 'kontext',
  event_type text NOT NULL,
  title text NOT NULL,
  description text,
  metadata jsonb DEFAULT '{}',
  created_at timestamptz DEFAULT now(),

  CONSTRAINT activity_events_source_check CHECK (source IN ('kontext', 'github')),
  CONSTRAINT activity_events_type_check CHECK (event_type IN (
    'repo_added', 'repo_indexed',
    'team_member_joined', 'team_invite_sent',
    'chat_session', 'prompt_generated',
    'push', 'pull_request', 'issue', 'create', 'release'
  ))
);

CREATE INDEX IF NOT EXISTS idx_activity_events_user_created
  ON public.activity_events(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_activity_events_user_source
  ON public.activity_events(user_id, source);

ALTER TABLE public.activity_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own activity" ON public.activity_events
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Enable Supabase Realtime for this table
ALTER PUBLICATION supabase_realtime ADD TABLE public.activity_events;

-- ────────────────────────────────────────────
-- 2. User Preferences table
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_preferences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  activity_filters jsonb DEFAULT '{
    "repo_added": true,
    "repo_indexed": true,
    "team_member_joined": true,
    "team_invite_sent": true,
    "chat_session": true,
    "prompt_generated": true,
    "push": true,
    "pull_request": true,
    "issue": true,
    "create": true,
    "release": true
  }'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own preferences" ON public.user_preferences
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ────────────────────────────────────────────
-- 3. Grants
-- ────────────────────────────────────────────
GRANT ALL ON TABLE public.activity_events TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.user_preferences TO anon, authenticated, service_role;
