-- ═══════════════════════════════════════════════════════════════════
-- Kontext v2 Migration: Sync Tracking, Timeline & Embedding Upgrade
-- ═══════════════════════════════════════════════════════════════════

-- ────────────────────────────────────────────
-- 1. Add sync tracking columns to repos table
-- ────────────────────────────────────────────
ALTER TABLE public.repos
  ADD COLUMN IF NOT EXISTS last_synced_sha text,
  ADD COLUMN IF NOT EXISTS watched_branch text,
  ADD COLUMN IF NOT EXISTS auto_sync_enabled boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS understanding_tier smallint DEFAULT 2,
  ADD COLUMN IF NOT EXISTS webhook_id bigint;

-- ────────────────────────────────────────────
-- 2. Create repo_commits table (Development Timeline)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.repo_commits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  repo_full_name text NOT NULL,
  sha text NOT NULL,
  message text NOT NULL,
  author_name text,
  author_avatar_url text,
  committed_at timestamptz NOT NULL,
  files_changed jsonb DEFAULT '[]',
  sync_triggered boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_id, repo_full_name, sha)
);

CREATE INDEX IF NOT EXISTS idx_repo_commits_lookup
  ON public.repo_commits(user_id, repo_full_name, committed_at DESC);

ALTER TABLE public.repo_commits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own commits" ON public.repo_commits
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ────────────────────────────────────────────
-- 3. Create webhook_events table (dedup + audit)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.webhook_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delivery_id text UNIQUE NOT NULL,
  repo_full_name text NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  processed boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.webhook_events ENABLE ROW LEVEL SECURITY;

-- Webhook events are server-managed only (no user RLS needed)
-- Service role will insert, no user access required

-- ────────────────────────────────────────────
-- 4. Upgrade vector dimension: 768 → 1536
-- ────────────────────────────────────────────
-- Drop the old IVFFlat index (depends on the old column type)
DROP INDEX IF EXISTS public.idx_repo_chunks_embedding;

-- Alter the embedding column to 3072 dimensions
ALTER TABLE public.repo_chunks
  ALTER COLUMN embedding TYPE extensions.vector(1536)
  USING NULL;
-- Note: USING NULL drops existing embeddings. This is intentional because
-- old 768-dim embeddings from text-embedding-004 are incompatible with
-- new 1536-dim embeddings from gemini-embedding-001.

-- Recreate using HNSW index (supports up to 4096 dims, better query perf than IVFFlat)
CREATE INDEX idx_repo_chunks_embedding
  ON public.repo_chunks
  USING hnsw (embedding extensions.vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- ────────────────────────────────────────────
-- 5. Update match_chunks RPC for 3072 dimensions
-- ────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.match_chunks(
  query_embedding extensions.vector,
  match_count integer DEFAULT 5,
  filter_repo text DEFAULT NULL,
  filter_user_id uuid DEFAULT NULL
)
RETURNS TABLE(
  id bigint,
  file_path text,
  content text,
  similarity double precision
)
LANGUAGE plpgsql
AS $$
begin
  return query
  select
    rc.id,
    rc.file_path,
    rc.content,
    1 - (rc.embedding <=> query_embedding) as similarity
  from public.repo_chunks rc
  where
    (filter_user_id is null or rc.user_id = filter_user_id)
    and (filter_repo is null or rc.repo_full_name = filter_repo)
  order by rc.embedding <=> query_embedding
  limit match_count;
end;
$$;
