-- Repo health checks and finding lifecycle

CREATE TABLE IF NOT EXISTS public.repo_check_configs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  repo_full_name text NOT NULL,
  check_type text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  trigger_mode text NOT NULL DEFAULT 'after_sync',
  notify_on_high boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT repo_check_configs_type_check CHECK (
    check_type IN ('security', 'optimization', 'consistency', 'change_impact')
  ),
  CONSTRAINT repo_check_configs_trigger_check CHECK (
    trigger_mode IN ('manual', 'after_sync', 'daily')
  ),
  UNIQUE(user_id, repo_full_name, check_type)
);

CREATE TABLE IF NOT EXISTS public.repo_check_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  repo_full_name text NOT NULL,
  trigger_mode text NOT NULL DEFAULT 'manual',
  status text NOT NULL DEFAULT 'queued',
  dedupe_key text,
  requested_check_types jsonb NOT NULL DEFAULT '[]'::jsonb,
  changed_files jsonb NOT NULL DEFAULT '[]'::jsonb,
  base_sha text,
  head_sha text,
  summary text,
  findings_total integer NOT NULL DEFAULT 0,
  new_findings integer NOT NULL DEFAULT 0,
  resolved_findings integer NOT NULL DEFAULT 0,
  unchanged_findings integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_message text,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT repo_check_runs_trigger_check CHECK (
    trigger_mode IN ('manual', 'after_sync', 'daily', 'mcp')
  ),
  CONSTRAINT repo_check_runs_status_check CHECK (
    status IN ('queued', 'running', 'completed', 'failed', 'skipped')
  ),
  UNIQUE(user_id, dedupe_key)
);

CREATE TABLE IF NOT EXISTS public.repo_check_findings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  repo_full_name text NOT NULL,
  check_type text NOT NULL,
  fingerprint text NOT NULL,
  title text NOT NULL,
  summary text NOT NULL,
  severity text NOT NULL DEFAULT 'medium',
  status text NOT NULL DEFAULT 'open',
  transition_state text NOT NULL DEFAULT 'new',
  confidence double precision NOT NULL DEFAULT 0.5,
  category text,
  file_path text,
  symbol text,
  evidence text,
  recommendation text,
  related_files jsonb NOT NULL DEFAULT '[]'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  first_seen_sha text,
  last_seen_sha text,
  fixed_in_sha text,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  opened_in_run_id bigint REFERENCES public.repo_check_runs(id) ON DELETE SET NULL,
  last_run_id bigint REFERENCES public.repo_check_runs(id) ON DELETE SET NULL,
  fixed_in_run_id bigint REFERENCES public.repo_check_runs(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT repo_check_findings_type_check CHECK (
    check_type IN ('security', 'optimization', 'consistency', 'change_impact')
  ),
  CONSTRAINT repo_check_findings_severity_check CHECK (
    severity IN ('low', 'medium', 'high', 'critical')
  ),
  CONSTRAINT repo_check_findings_status_check CHECK (
    status IN ('open', 'resolved')
  ),
  CONSTRAINT repo_check_findings_transition_check CHECK (
    transition_state IN ('new', 'persistent', 'regressed', 'resolved')
  ),
  UNIQUE(user_id, repo_full_name, check_type, fingerprint)
);

CREATE INDEX IF NOT EXISTS idx_repo_check_configs_lookup
  ON public.repo_check_configs(user_id, repo_full_name);

CREATE INDEX IF NOT EXISTS idx_repo_check_runs_lookup
  ON public.repo_check_runs(user_id, repo_full_name, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_repo_check_findings_lookup
  ON public.repo_check_findings(user_id, repo_full_name, status, severity);

ALTER TABLE public.repo_check_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.repo_check_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.repo_check_findings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own repo check configs" ON public.repo_check_configs
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own repo check runs" ON public.repo_check_runs
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own repo check findings" ON public.repo_check_findings
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.activity_events
  DROP CONSTRAINT IF EXISTS activity_events_type_check;

ALTER TABLE public.activity_events
  ADD CONSTRAINT activity_events_type_check CHECK (
    event_type IN (
      'repo_added',
      'repo_deleted',
      'repo_indexed',
      'repo_synced',
      'team_member_joined',
      'team_invite_sent',
      'chat_session',
      'prompt_generated',
      'push',
      'pull_request',
      'issue',
      'create',
      'release',
      'workflow_run',
      'repo_check_completed'
    )
  );

GRANT ALL ON TABLE public.repo_check_configs TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.repo_check_runs TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.repo_check_findings TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.repo_check_configs_id_seq TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.repo_check_runs_id_seq TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.repo_check_findings_id_seq TO anon, authenticated, service_role;
