-- Shared repo jobs plus onboarding templates, versions, assignments, and attempts

CREATE TABLE IF NOT EXISTS public.repo_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  repo_full_name text NOT NULL,
  job_type text NOT NULL,
  trigger text NOT NULL DEFAULT 'manual',
  status text NOT NULL DEFAULT 'queued',
  title text,
  progress_percent integer NOT NULL DEFAULT 0,
  dedupe_key text,
  result_summary text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_message text,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT repo_jobs_type_check CHECK (
    job_type IN (
      'ingest',
      'sync',
      'repo_check',
      'onboarding_generate',
      'onboarding_assign',
      'architecture_refresh'
    )
  ),
  CONSTRAINT repo_jobs_trigger_check CHECK (
    trigger IN ('manual', 'webhook', 'schedule', 'mcp', 'system', 'invite', 'sync')
  ),
  CONSTRAINT repo_jobs_status_check CHECK (
    status IN ('queued', 'running', 'completed', 'failed', 'skipped')
  ),
  CONSTRAINT repo_jobs_progress_check CHECK (
    progress_percent >= 0 AND progress_percent <= 100
  ),
  UNIQUE(user_id, dedupe_key)
);

CREATE TABLE IF NOT EXISTS public.onboarding_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  repo_full_name text NOT NULL,
  title text NOT NULL DEFAULT 'Repository onboarding',
  description text,
  status text NOT NULL DEFAULT 'draft',
  current_version integer NOT NULL DEFAULT 0,
  active_version_id bigint,
  source_template_id bigint REFERENCES public.onboarding_templates(id) ON DELETE SET NULL,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT onboarding_templates_status_check CHECK (
    status IN ('draft', 'published', 'archived')
  )
);

CREATE TABLE IF NOT EXISTS public.onboarding_template_steps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  repo_full_name text NOT NULL,
  template_id bigint NOT NULL REFERENCES public.onboarding_templates(id) ON DELETE CASCADE,
  step_order integer NOT NULL,
  step_type text NOT NULL DEFAULT 'content',
  title text NOT NULL,
  description text,
  content text,
  quiz_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT onboarding_template_steps_type_check CHECK (
    step_type IN ('content', 'guided_explore', 'quiz', 'acknowledgement')
  ),
  UNIQUE(template_id, step_order)
);

CREATE TABLE IF NOT EXISTS public.onboarding_template_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  repo_full_name text NOT NULL,
  template_id bigint NOT NULL REFERENCES public.onboarding_templates(id) ON DELETE CASCADE,
  version_number integer NOT NULL,
  title text NOT NULL,
  description text,
  steps jsonb NOT NULL DEFAULT '[]'::jsonb,
  step_count integer NOT NULL DEFAULT 0,
  published_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(template_id, version_number)
);

ALTER TABLE public.onboarding_templates
  DROP CONSTRAINT IF EXISTS onboarding_templates_active_version_id_fkey;

ALTER TABLE public.onboarding_templates
  ADD CONSTRAINT onboarding_templates_active_version_id_fkey
  FOREIGN KEY (active_version_id)
  REFERENCES public.onboarding_template_versions(id)
  ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS public.onboarding_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  repo_full_name text NOT NULL,
  template_id bigint REFERENCES public.onboarding_templates(id) ON DELETE SET NULL,
  template_version_id bigint REFERENCES public.onboarding_template_versions(id) ON DELETE SET NULL,
  invite_id bigint REFERENCES public.team_invites(id) ON DELETE SET NULL,
  assignee_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  assignee_github_username text,
  assigned_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  role_target text NOT NULL DEFAULT 'member',
  status text NOT NULL DEFAULT 'assigned',
  progress_percent integer NOT NULL DEFAULT 0,
  current_step integer NOT NULL DEFAULT 0,
  score numeric(5, 2),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT onboarding_assignments_role_check CHECK (
    role_target IN ('admin', 'member', 'viewer')
  ),
  CONSTRAINT onboarding_assignments_status_check CHECK (
    status IN ('assigned', 'in_progress', 'completed', 'overdue', 'cancelled')
  ),
  CONSTRAINT onboarding_assignments_progress_check CHECK (
    progress_percent >= 0 AND progress_percent <= 100
  ),
  UNIQUE(user_id, repo_full_name, invite_id)
);

CREATE TABLE IF NOT EXISTS public.onboarding_step_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  repo_full_name text NOT NULL,
  assignment_id bigint NOT NULL REFERENCES public.onboarding_assignments(id) ON DELETE CASCADE,
  step_order integer NOT NULL,
  step_title text,
  attempt_number integer NOT NULL DEFAULT 1,
  passed boolean NOT NULL DEFAULT false,
  score numeric(5, 2),
  response jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT onboarding_step_attempts_attempt_check CHECK (attempt_number >= 1),
  UNIQUE(assignment_id, step_order, attempt_number)
);

ALTER TABLE public.team_invites
  ADD COLUMN IF NOT EXISTS onboarding_template_version_id bigint
  REFERENCES public.onboarding_template_versions(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_repo_jobs_lookup
  ON public.repo_jobs(user_id, repo_full_name, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_onboarding_templates_lookup
  ON public.onboarding_templates(user_id, repo_full_name, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_onboarding_template_steps_lookup
  ON public.onboarding_template_steps(user_id, repo_full_name, template_id, step_order);

CREATE INDEX IF NOT EXISTS idx_onboarding_versions_lookup
  ON public.onboarding_template_versions(user_id, repo_full_name, template_id, version_number DESC);

CREATE INDEX IF NOT EXISTS idx_onboarding_assignments_lookup
  ON public.onboarding_assignments(user_id, repo_full_name, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_onboarding_attempts_lookup
  ON public.onboarding_step_attempts(user_id, repo_full_name, assignment_id, step_order);

ALTER TABLE public.repo_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding_template_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding_template_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding_step_attempts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own repo jobs" ON public.repo_jobs
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own onboarding templates" ON public.onboarding_templates
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own onboarding steps" ON public.onboarding_template_steps
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own onboarding versions" ON public.onboarding_template_versions
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own onboarding assignments" ON public.onboarding_assignments
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own onboarding attempts" ON public.onboarding_step_attempts
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

GRANT ALL ON TABLE public.repo_jobs TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.onboarding_templates TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.onboarding_template_steps TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.onboarding_template_versions TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.onboarding_assignments TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.onboarding_step_attempts TO anon, authenticated, service_role;

GRANT ALL ON SEQUENCE public.repo_jobs_id_seq TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.onboarding_templates_id_seq TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.onboarding_template_steps_id_seq TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.onboarding_template_versions_id_seq TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.onboarding_assignments_id_seq TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.onboarding_step_attempts_id_seq TO anon, authenticated, service_role;
