import { NextResponse } from "next/server";

// Mock repository data for frontend development
const mockRepos = [
  {
    id: 1,
    full_name: "acme/web-platform",
    name: "web-platform",
    owner: "acme",
    description: "Main web platform built with Next.js 14, TypeScript, and Tailwind CSS",
    language: "TypeScript",
    stargazers_count: 342,
    forks_count: 28,
    updated_at: "2026-03-27T14:30:00Z",
    indexed: true,
    indexing: false,
    chunk_count: 1847,
  },
  {
    id: 2,
    full_name: "acme/api-gateway",
    name: "api-gateway",
    owner: "acme",
    description: "REST & GraphQL API gateway with Redis caching and rate limiting",
    language: "TypeScript",
    stargazers_count: 156,
    forks_count: 12,
    updated_at: "2026-03-26T09:15:00Z",
    indexed: true,
    indexing: false,
    chunk_count: 923,
  },
  {
    id: 3,
    full_name: "acme/ml-pipeline",
    name: "ml-pipeline",
    owner: "acme",
    description: "Machine learning data pipeline for recommendation engine",
    language: "Python",
    stargazers_count: 89,
    forks_count: 7,
    updated_at: "2026-03-25T18:00:00Z",
    indexed: true,
    indexing: false,
    chunk_count: 612,
  },
  {
    id: 4,
    full_name: "acme/mobile-app",
    name: "mobile-app",
    owner: "acme",
    description: "Cross-platform mobile application built with React Native",
    language: "TypeScript",
    stargazers_count: 203,
    forks_count: 19,
    updated_at: "2026-03-28T10:00:00Z",
    indexed: false,
    indexing: false,
    chunk_count: 0,
  },
  {
    id: 5,
    full_name: "acme/infra-config",
    name: "infra-config",
    owner: "acme",
    description: "Terraform & Kubernetes infrastructure configuration",
    language: "Go",
    stargazers_count: 45,
    forks_count: 3,
    updated_at: "2026-03-20T08:30:00Z",
    indexed: false,
    indexing: false,
    chunk_count: 0,
  },
  {
    id: 6,
    full_name: "acme/design-system",
    name: "design-system",
    owner: "acme",
    description: "Shared UI component library and design tokens",
    language: "TypeScript",
    stargazers_count: 178,
    forks_count: 15,
    updated_at: "2026-03-24T12:45:00Z",
    indexed: false,
    indexing: true,
    chunk_count: 0,
  },
  {
    id: 7,
    full_name: "acme/rust-engine",
    name: "rust-engine",
    owner: "acme",
    description: "High-performance computation engine written in Rust",
    language: "Rust",
    stargazers_count: 410,
    forks_count: 34,
    updated_at: "2026-03-22T16:20:00Z",
    indexed: false,
    indexing: false,
    chunk_count: 0,
  },
  {
    id: 8,
    full_name: "acme/docs",
    name: "docs",
    owner: "acme",
    description: "Developer documentation and API reference",
    language: "JavaScript",
    stargazers_count: 67,
    forks_count: 5,
    updated_at: "2026-03-21T11:10:00Z",
    indexed: false,
    indexing: false,
    chunk_count: 0,
  },
];

export async function GET() {
  return NextResponse.json({ repos: mockRepos });
}
